app.name=\u591A\u7EF4\u5206\u6790
#token.expire.minute=60

#\u046D\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD1\uFFFD\uFFFD10\uFFFD\uB8E8nginx\uFFFD\uFFFD5\uFFFD\uFFFD\uFFFD\u04E3\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\uFFFD\u03A2\uFFFD\uFFFD\u01F0\u04BB\uFFFD\u38E9
#presto.query.timeout = 23
#presto.timeout.message = The query time has exceeded 4 minutes, the system interrupts the query!