package com.bi.queryer.sys.base.proxy;

import java.sql.*;
import java.util.concurrent.atomic.AtomicBoolean;

/**
 * @Auther: contributor
 * @Date: 2024/8/2 14:51
 * @Description:
 */
public class StatementProxy implements Statement {
    private final Statement rawStatement;

    private final AtomicBoolean isCancelled = new AtomicBoolean(false);

    protected StatementProxy(Statement statement) {
        this.rawStatement = statement;
    }

    @Override
    public ResultSet executeQuery(String sql) throws SQLException {
        return rawStatement.executeQuery(sql);
    }

    @Override
    public int executeUpdate(String sql) throws SQLException {
        return rawStatement.executeUpdate(sql);
    }

    @Override
    public void close() throws SQLException {
        rawStatement.close();
        isCancelled.set(true);
    }

    @Override
    public int getMaxFieldSize() throws SQLException {
        return rawStatement.getMaxFieldSize();
    }

    @Override
    public void setMaxFieldSize(int max) throws SQLException {
        rawStatement.setMaxFieldSize(max);
    }

    @Override
    public int getMaxRows() throws SQLException {
        return rawStatement.getMaxRows();
    }

    @Override
    public void setMaxRows(int max) throws SQLException {
        rawStatement.setMaxRows(max);
    }

    @Override
    public void setEscapeProcessing(boolean enable) throws SQLException {
        rawStatement.setEscapeProcessing(enable);
    }

    @Override
    public int getQueryTimeout() throws SQLException {
        return rawStatement.getQueryTimeout();
    }

    @Override
    public void setQueryTimeout(int seconds) throws SQLException {
        rawStatement.setQueryTimeout(seconds);
    }

    @Override
    public void cancel() throws SQLException {
        rawStatement.cancel();
        isCancelled.set(true);
    }

    @Override
    public SQLWarning getWarnings() throws SQLException {
        return rawStatement.getWarnings();
    }

    @Override
    public void clearWarnings() throws SQLException {
        rawStatement.clearWarnings();
    }

    @Override
    public void setCursorName(String name) throws SQLException {
        rawStatement.setCursorName(name);
    }

    @Override
    public boolean execute(String sql) throws SQLException {
        return rawStatement.execute(sql);
    }

    @Override
    public ResultSet getResultSet() throws SQLException {
        return rawStatement.getResultSet();
    }

    @Override
    public int getUpdateCount() throws SQLException {
        return rawStatement.getUpdateCount();
    }

    @Override
    public boolean getMoreResults() throws SQLException {
        return rawStatement.getMoreResults();
    }

    @Override
    public void setFetchDirection(int direction) throws SQLException {
        rawStatement.setFetchDirection(direction);
    }

    @Override
    public int getFetchDirection() throws SQLException {
        return rawStatement.getFetchDirection();
    }

    @Override
    public void setFetchSize(int rows) throws SQLException {
        rawStatement.setFetchSize(rows);
    }

    @Override
    public int getFetchSize() throws SQLException {
        return rawStatement.getFetchSize();
    }

    @Override
    public int getResultSetConcurrency() throws SQLException {
        return rawStatement.getResultSetConcurrency();
    }

    @Override
    public int getResultSetType() throws SQLException {
        return rawStatement.getResultSetType();
    }

    @Override
    public void addBatch(String sql) throws SQLException {
        rawStatement.addBatch(sql);
    }

    @Override
    public void clearBatch() throws SQLException {
        rawStatement.clearBatch();
    }

    @Override
    public int[] executeBatch() throws SQLException {
        return rawStatement.executeBatch();
    }

    @Override
    public Connection getConnection() throws SQLException {
        return rawStatement.getConnection();
    }

    @Override
    public boolean getMoreResults(int current) throws SQLException {
        return rawStatement.getMoreResults(current);
    }

    @Override
    public ResultSet getGeneratedKeys() throws SQLException {
        return rawStatement.getGeneratedKeys();
    }

    @Override
    public int executeUpdate(String sql, int autoGeneratedKeys) throws SQLException {
        return rawStatement.executeUpdate(sql, autoGeneratedKeys);
    }

    @Override
    public int executeUpdate(String sql, int[] columnIndexes) throws SQLException {
        return rawStatement.executeUpdate(sql, columnIndexes);
    }

    @Override
    public int executeUpdate(String sql, String[] columnNames) throws SQLException {
        return rawStatement.executeUpdate(sql, columnNames);
    }

    @Override
    public boolean execute(String sql, int autoGeneratedKeys) throws SQLException {
        return rawStatement.execute(sql, autoGeneratedKeys);
    }

    @Override
    public boolean execute(String sql, int[] columnIndexes) throws SQLException {
        return rawStatement.execute(sql, columnIndexes);
    }

    @Override
    public boolean execute(String sql, String[] columnNames) throws SQLException {
        return rawStatement.execute(sql, columnNames);
    }

    @Override
    public int getResultSetHoldability() throws SQLException {
        return rawStatement.getResultSetHoldability();
    }

    @Override
    public boolean isClosed() throws SQLException {
        return rawStatement.isClosed() || isCancelled.get();
    }

    @Override
    public void setPoolable(boolean poolable) throws SQLException {
        rawStatement.setPoolable(poolable);
    }

    @Override
    public boolean isPoolable() throws SQLException {
        return rawStatement.isPoolable();
    }

    @Override
    public void closeOnCompletion() throws SQLException {
        rawStatement.closeOnCompletion();
    }

    @Override
    public boolean isCloseOnCompletion() throws SQLException {
        return rawStatement.isCloseOnCompletion();
    }

    @Override
    public <T> T unwrap(Class<T> iface) throws SQLException {
        return rawStatement.unwrap(iface);
    }

    @Override
    public boolean isWrapperFor(Class<?> iface) throws SQLException {
        return rawStatement.isWrapperFor(iface);
    }
}